### ISSUE TITLE
Can this use GPU for encoding?

### ISSUE THREAD

**Issue by tyeeman** [59de44955ebd/QMediaTool#1]
Update - just tried to run on Win7 64bit and got this error - 
<img width="347" alt="2022-04-08_210430" src="https://user-images.githubusercontent.com/4469306/162555677-64ece870-b8f9-4480-bb58-1412e00dd7df.png">

Anything come to mind? That file does not exist on my PC.

Update2 - found and installed that file and got this error - 

<img width="337" alt="2022-04-08_213704" src="https://user-images.githubusercontent.com/4469306/162556566-5ceaeed4-d806-4f21-a382-e0a7691a6192.png">

Update3 - Win7 only works with Python up to version 3.8.9, so I'm SOL.

Maybe Not. I see I can build it myself. We'll see.

OK, it built fine! Thanks. Only thing is with my PC I have fonts set to 150% but your app ignores this. I can hardly read the text.

**Comment by tyeeman** [comment]
1. Well, I upgraded to Win10 and now it works! Just trying it out and it looks like it's not set up for high dpi video settings. If I use windows built in ```change high dpi settings```, that nearly makes it work properly except the very bottom is cut off below ```output directory```. If I double click the top bar twice, everything shows but the notes are cut off at the bottom. 

2. My first file has a space and the error I get is 
```
G:/-----New After May 4 2020/QMediaTool/resources/bin/win/ffmpeg_prog/ffmpeg_prog: line 2: "G:/-----New: No such file or directory
```
I changed the path of my file so it has no spaces and I still get this error. It must be the path of the ffmpeg exe that is the problem?

```$FFMPEG -hide_banner -progress tcp://localhost:9999 "$@"```

3. ```Add task to task queue``` does not add it to the task queue window.

**Comment by 59de44955ebd** [comment]
Hi, issues 2 and 3 should be fixed by now, please try latest (release) version v0.7.

2.) was indeed not about spaces in media file pathes, but instead about spaces in the path to the ffmpeg folder resp. the main app folder, some bash weirdness, the env var $FFMPEG contained the path to ffmpeg correctly escaped with quotes, but the "ffmpeg_prog" shell script couln't handle those, so I had to first remove and then re-add the quotes by changing the script to this:
```
#!/bin/bash
FFMPEG="${FFMPEG%\"}"
FFMPEG="${FFMPEG#\"}"
"$FFMPEG" -hide_banner -progress tcp://localhost:9999 "$@"
```

3.) was just a typo, at some point I had renamed TaskManager's method "addTask" to "add_task", but forgotten to also rename it in main.py.

Concerning 1), I don't have a Windows PC with HiDPI display, but only an iMac with integrated Retina display and can confirm that HiDPI works fine in macOS. Propably just a single line is missing in main.py to make it HiDPI compatible In Windows, but for now I would recommend to simply change the HiDPI settings for QMediaTool.exe in Explorer's context menu (Compatibility mode -> HiDPI settings -> Overwrite -> System).

Concerning the original issues title, of course the tool supports GPU encoding:

In Windows the enclosed ffmpeg version supports both H.264 and HEVC/H.265 encoding either via (not too old) NVIDIA, AMD or Intel GPUs. In addition it also contains the advanced GPU encoding tools NVEnc, VCEEnc and QSVEnc (https://github.com/rigaya) for the same 3 GPU types, that allow more finetuning than ffmpeg does.

In macOS GPU encoding is supported via Apple's "VideoToolbox" technology integrated into ffmpeg.

In the latest release version I also added 2 new categories to the preset database, "Video - Encoding via GPU (Windows)" and "Video - Encoding via GPU (macOS)".

**Comment by tyeeman** [comment]
OK, thanks for all that. Just trying to run the new version and get 6 virusT detections. Strange! They're most likely false positives.

**Comment by 59de44955ebd** [comment]
It surely is, but if you have doubts, clone the repo instead and run "make_dist_win.cmd", which will create a new .exe in folder "dist".
